deploy:
  branch:
    server: drupal7.examples.zen.ci
    username: zenci
    dir: '{home}/github/{repo_owner}/{repo_name}/branch/{branch}'
    env_vars:
      docroot: '{home}/domains/drupal7.examples.zen.ci'
      domain: 'drupal7.examples.zen.ci'
      database_name: zenci_drupal
      database_user: zenci_drupal
      database_pass: DBPASSWORD
      account_user: admin
      account_mail: admin@zen.ci
      account_pass: REPLACE_WITH_ADMIN_PASSWORD
      site_mail: noreply@zen.ci
      site_name: 'drupal-starter-kit example 1.'
      default_theme: "bootstrap_lite"
      enable_devel: "yes"      
    scripts:
      init: '{deploy_dir}/scripts/deploy_init.sh'
      after: '{deploy_dir}/scripts/deploy_update.sh'
pull_request:
    server: qa.drupal7.examples.zen.ci
    username: test
    dir: '{home}/github/{repo_owner}/{repo_name}/pr/{pr_number}'
    env_vars:
      docroot: '{home}/domains/{pr_number}.{branch}.qa.drupal7.examples.zen.ci'
      domain: '{pr_number}.{branch}.qa.drupal7.examples.zen.ci'
      database_name: 'test_{branch}_{pr_number}'
      database_user: 'test_{branch}_{pr_number}'
      database_pass: 'test_{branch}_{pr_number}'
      account_user: admin
      account_mail: admin@zen.ci
      account_pass: REPLACE_WITH_ADMIN_PASSWORD
      site_mail: noreply@zen.ci
      site_name: '{pr_number} {branch} QA site for {repo_owner}/{repo_name}'
      default_theme: "bootstrap_lite"
      enable_devel: "yes"
    scripts:
      init: '{deploy_dir}/scripts/qa_deploy_init.sh'
      after: '{deploy_dir}/scripts/deploy_update.sh'
      remove: '{deploy_dir}/scripts/qa_deploy_remove.sh'
