deploy:
  branch:
    server: drupal7.examples.zen.ci
    username: zenci
    dir: '{home}/github/{repo_owner}/{repo_name}/branch/{branch}'
    env_vars:
      docroot: '{home}/domains/drupal7.examples.zen.ci'
      domain: 'drupal7.examples.zen.ci'
      database_name: zenci_drupal
      database_user: zenci_drupal
      database_pass: DBPASSWORD
      account_user: admin
      account_mail: admin@zen.ci
      account_pass: REPLACE_WITH_ADMIN_PASSWORD
      site_mail: noreply@zen.ci
      site_name: 'drupal-starter-kit example 1.'
      default_theme: "bootstrap_lite"
      enable_devel: "yes"      
    scripts:
      init: '{deploy_dir}/scripts/deploy_init.sh'
      after: '{deploy_dir}/scripts/deploy_update.sh'
